export const deluxeRooms = [
  {
    id: 1001,
    image: "deluxe1.jpg",
    title: "Classic Single Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 1002,
    image: "deluxe2.jpg",
    title: "Couple Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 1003,
    image: "deluxe3.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 1004,
    image: "deluxe4.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 1005,
    image: "deluxe5.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 1006,
    image: "deluxe6.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 1007,
    image: "deluxe7.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 1008,
    image: "deluxe8.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 1009,
    image: "deluxe9.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 1010,
    image: "deluxe10.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
];

export const executiveRooms = [
  {
    id: 2001,
    image: "executive1.jpg",
    title: "Classic Single Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2002,
    image: "executive2.jpg",
    title: "Couple Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2003,
    image: "executive3.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2004,
    image: "executive4.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2005,
    image: "executive5.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2006,
    image: "executive6.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2007,
    image: "executive7.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2008,
    image: "executive8.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2009,
    image: "executive9.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2010,
    image: "executive10.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2011,
    image: "executive11.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2012,
    image: "executive12.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {id: 2013,
    image: "executive13.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2014,
    image: "executive14.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2015,
    image: "executive15.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2016,
    image: "executive16.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
];

export const luxuryRooms = [
  {
    id: 3001,
    image: "luxury1.jpg",
    title: "Classic Single Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 3002,
    image: "luxury2.jpg",
    title: "Couple Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 3003,
    image: "luxury3.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 3004,
    image: "luxury4.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 3005,
    image: "luxury5.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 3006,
    image: "luxury6.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 3007,
    image: "luxury7.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
];

export const standardRooms = [
  {
    id: 4001,
    image: "standard1.jpg",
    title: "Classic Single Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 4002,
    image: "standard2.jpg",
    title: "Couple Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 4003,
    image: "standard3.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 4004,
    image: "standard4.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 4005,
    image: "standard5.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 4006,
    image: "standard6.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 4007,
    image: "standard7.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
];
